name: Java CI with Gradle
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
      GH_TOKEN_PUBLIC_REPOS_READONLY: ${{ secrets.GH_TOKEN_PUBLIC_REPOS_READONLY }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      TESTCONTAINERS_RYUK_DISABLED: true
      PREDICTIVE_TEST_SELECTION: "${{ github.event_name == 'pull_request' && 'true' || 'false' }}"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: XXX
      AWS_SECRET_ACCESS_KEY: YYY
      AWS_REGION: us-east-1
    steps:
      # https://github.com/actions/virtual-environments/issues/709
      - name: "🗑 Free disk space"
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          df -h

      - name: "📥 Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "🔧 Setup GraalVM CE"
        uses: graalvm/setup-graalvm@v1.1.2
        with:
          distribution: 'graalvm-community'
          java-version: ${{ matrix.java }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "🔧 Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "🛠 Build with Gradle"
        id: gradle
        run: |
          ./gradlew build --continue

      - name: "⏫ Upload spock reports"
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '*/build/reports/tests/test/index.html'